afternoon_edit: false
capital:
- Lesotho
- Africa
- Maseru
classic:
- Tokelau
- '690'
- Oceania
- 1411
- 12
- UTC+13:00
dns:
- Bouvet Island
- ''
- .bv
flag:
- Latvia
- Europe
- LV
map:
- United Arab Emirates
- 24
- 54
- Asia
morning_edit: true
